export const projects = [
  {
    name: "Jude Solar",
    slug: "jude-solar",
    show: "Premium solar installations for homes & businesses. Cut your electricity costs by up to 80%.",
    desc: "Premium solar solutions for homes and businesses. The company delivers high-quality solar installations designed to reduce electricity costs by up to 80%, providing long-term energy independence and sustainability.",
    lang: ["React", "TypeScript", "Cloudinary", "Docker", "Whatsapp Web"],
    img: "judesolar.png",
    img2: "judesolar2.png",
    img3: "judesolar3.png",
    link: "https://www.judesolar.com/",
    git: "https://github.com/ZENDSOLV-TECHNOLOGIES-LIMITED/jude-solar",
  },
  {
    name: "ZendSolv",
    slug: "zendsolv",
    show: "A passionate team of developers, designers, and AI enthusiasts dedicated to turning complex problems into elegant, scalable solutions.",
    desc: "Implemented a production-grade company website for a digital solutions firm specializing in web development and end-to-end AI systems, delivering real-world software for real clients and measurable business impact.",
    lang: [
      "Next.js",
      "Node.js",
      "MongoDB",
      "TypeScript",
      "Cloudinary",
      "Docker",
    ],
    img: "zendsolv.png",
    img2: "zendsolv2.png",
    img3: "zendsolv3.png",
    link: "https://www.zendsolv.com/",
    git: "https://github.com/SteeveSticks",
  },
  {
    name: "StartupFounder",
    slug: "startup-founder",
    show: "Sanity used for dynamic sections, animation with Framer Motion aligning with my goal to empower developers in London’s tech scene",
    desc: "A beautifully designed startup platform for developers to showcase their startups and for users to discover innovative tech projects. Built using modern frameworks for performance and scalability.",
    lang: [
      "Next.js",
      "TypeScript",
      "Tailwind CSS 4",
      "Sanity",
      "Sentry",
      "Zod",
      "NextAuth",
    ],
    img: "startupFounderimg.png",
    img2: "startupfounder2.png",
    img3: "startupfounder3.png",
    link: "https://startup-founders-app.vercel.app/",
    git: "https://github.com/SteeveSticks/STARTUP-FULLSTACK-APP",
  },
  {
    name: "Halamd🍀",
    slug: "ai-mood-stylist",
    show: "Built with Next.js and Tailwind, leveraging OpenAI’s GPT and DALL·E 3 to suggest and visualize stylish outfits tailored to a user’s mood.",
    desc: "Halamd is an AI Mood Stylist your personal, intelligent fashion companion that curates outfits based on your mood, style preferences, and the occasion. Using advanced AI and machine learning, it analyzes your emotional state and suggests clothing combinations that not only match your vibe but also boost your confidence. Whether you’re feeling bold, relaxed, romantic, or ready to conquer the world, AI Mood Stylist ensures you step out looking as good as you feel — every single day.",
    lang: [
      "Next.js",
      "TypeScript",
      "Tailwind CSS 4",
      "Framer Motion",
      "OpenAI",
      "State Management & UX",
      "Vercel",
      "Github",
    ],
    img: "halamd-image.png",
    img2: "halmand2.png",
    img3: "halmad3.png",
    link: "https://halamdcom.vercel.app/",
    git: "https://github.com/SteeveSticks/Assistly-Ai-Agent-Bot",
  },
  {
    name: "Notion App Clone",
    slug: "Notion",
    show: "Implemented real-time collaboration, user typing indicators, OpenAI-like cloudflare language, and OpenAI chat integration, worked with Liveblocks and Firebase",
    desc: "A collaborative document editing app similar to Notion, featuring real-time user presence, typing indicators, and AI-powered chat functionality using cloudflare language and OpenAI integration.",
    lang: [
      "Next.js",
      "Clerk",
      "Tailwind CSS",
      "Shadcn",
      "Liveblocks",
      "Firebase",
      "Hono",
      "Cloudflare Workers",
      "OpenAI API",
      "Vercel",
    ],
    img: "notionclone.png",
    link: "https://notion-clone-psi-gray.vercel.app/",
    git: "https://github.com/SteeveSticks/NOTION-CLONE",
    problem:
      "Many collaborative tools lack seamless real-time interaction and advanced AI assistance, making it hard for teams to work efficiently on documents. Users often face delays in seeing edits or lack smart suggestions, reducing productivity.",
    solution:
      "I built a Notion-like clone using React with TypeScript, integrating Liveblocks for real-time collaboration and typing indicators, allowing users to see each other's edits instantly. Clerk handles user authentication and Firebase handles document storage. I added an OpenAI-like chat feature using Cloudflare Workers for language processing, enabling smart document suggestions and conversations. This solution enhances teamwork and productivity, built with a focus on real-time performance and AI-driven assistance.",
  },
  {
    name: "Job Portal",
    slug: "job-portal",
    show: " Real-world use case, responsive UI, auth + protected routes, elegant dashboard",
    desc: "A fully responsive job platform with authentication, dashboards for job seekers and recruiters, and smooth UI/UX built with modern best practices.",
    lang: [
      "React",
      "Tailwind CSS 4",
      "MongoDB",
      "Express",
      "Cloudinary",
      "GoogleOAuth",
    ],
    img: "job-portalimg.png",
    link: "https://job-portal-frontend-three-orcin.vercel.app/",
    git: "https://github.com/SteeveSticks/job-portal-mern-app",
    problem:
      "While exploring career opportunities, I noticed that job seekers often struggle with scattered job listings across multiple platforms, leading to missed opportunities. Recruiters, on the other hand, face challenges managing high volumes of applications without streamlined tools, resulting in inefficient hiring processes.",
    solution:
      "To address this, I developed the Job Portal, a centralized platform that simplifies job searching and recruitment. For job seekers, I implemented a responsive React frontend with Tailwind CSS 4 for a smooth, mobile-friendly UI, allowing easy browsing and application submission. For recruiters, I built elegant dashboards using MongoDB and Express to manage listings and candidates efficiently. GoogleOAuth ensures secure authentication, while Cloudinary handles image uploads for profiles and job posts. By integrating protected routes, I ensured only authorized users access sensitive features, reducing friction and enhancing user trust.",
  },
  {
    name: "Bookstore App",
    slug: "bookstore-app",
    show: " Clean full-stack setup, good backend experience",
    desc: "A full-stack bookstore application with user authentication, book management, and cart system. Built to reinforce backend understanding and deployment flow.",
    lang: [
      "React",
      "Node.js",
      "MongoDB",
      "Express",
      "Tailwind CSS 3",
      "Redux",
      "Firebase",
    ],
    img: "bookstoreimg.png",
    link: "https://stephen-book-app.vercel.app/",
    git: "https://github.com/SteeveSticks/book-app-frontend",
    problem:
      "I observed that small bookstores often struggle with manual inventory management and lack user-friendly online stores, leading to lost sales. Customers also face challenges finding and purchasing books due to outdated or complex e-commerce systems.",
    solution:
      "To tackle this, I developed the Bookstore App, a full-stack solution streamlining bookstore operations and customer purchases. The frontend, built with React and Tailwind CSS 3, offers a clean interface for browsing books and managing carts, with Redux handling state for seamless interactions. On the backend, Node.js, Express, and MongoDB manage book inventory and user data, while Firebase provides secure authentication. I optimized the deployment flow with Vercel, ensuring fast access. This app simplifies inventory updates for owners and enhances the shopping experience for customers, boosting sales efficiency.",
  },
  {
    name: "Pentagon Tokens",
    slug: "pentagon-tokens",
    show: "Live contact form with email integration",
    desc: "Diving into Web3. A sleek marketing website for a crypto project, built for a freelance client. Optimized for performance and responsiveness.",
    lang: [
      "React",
      "Node.js",
      "MongoDB",
      "Express.js",
      "Tailwind CSS 3",
      "Cloudinary",
      "EmailJS",
    ],
    img: "pentagonsTokenimg.png",
    link: "https://crypto-website-frontend-one.vercel.app/",
    git: "https://github.com/SteeveSticks/CRYPTO-WEBSITE-FRONTEND",
    problem:
      "While working with a freelance client in the Web3 space, I noticed that many crypto projects suffer from unprofessional or inaccessible websites, which undermines their credibility and deters potential investors or users from engaging with their vision.",
    solution:
      "I built Pentagon Tokens, a responsive marketing website to elevate the client’s crypto project. Using React and Tailwind CSS 3, I created a sleek, mobile-friendly frontend optimized for performance, with Cloudinary managing high-quality images. The backend, powered by Node.js, Express, and MongoDB, handles data efficiently. I integrated EmailJS for a live contact form, enabling direct user inquiries that boosted engagement by 20% based on client feedback. This solution enhanced the project’s professional image and accessibility, attracting more stakeholders.",
  },
];
